//
//  CrazyButtonStyleKit.h
//  ProjectName
//
//  Created by AuthorName on 12/1/15.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface CrazyButtonStyleKit : NSObject

// Drawing Methods
+ (void)drawCanvas1;

@end
