//
//  StyleKitTrial.h
//  ProjectName
//
//  Created by AuthorName on 11/29/15.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKitTrial : NSObject

// Drawing Methods
+ (void)drawWhereAreYouButton;

@end
